apiVersion: cabourotte.mcorbin.fr/v1
kind: Healthcheck
metadata:
  name: healthcheck-sample
  namespace: default
spec:
  dns-checks:
    - name: "mcorbin-dns-check"
    # The healthcheck description
      description: "dns healthcheck example"
    # The healthcheck domain
      domain: "mcorbin.fr"
    # The healthcheck interval
      interval: "5s"
    # A list of IPs (v4 or v6) which will be compared to the
    # DNS lookup results. The healthcheck will fail if the IPs defined
    # in this list are not returned
      expected-ips:
        - 165.1.3.4
    # Labels for this healthcheck. It will be used in logging and in
    # exporters (optional)
      labels:
        environment: prod

